level_task:
  description: "Assess the user's initial proficiency level in {{ language }}."
  input_template: |
    Analyze the following text written by the user in {{ language }}:
    "{{ text }}"

    Based only on the {{ language }} language, provide:
    - Detailed feedback highlighting common mistakes.
    - An estimated proficiency level (Beginner, Intermediate, Advanced, etc.).
    - Practical improvement tips specifically for {{ language }}.

    Important rules:
    - Do not evaluate content, only language proficiency.
    - Keep the feedback clear and concise, without unrelated comments.
    - Respond exclusively in English.

  expected_output: "A detailed report with feedback, estimated level, and practical improvement suggestions."

tip_task:
  description: "Send a daily language learning tip and a cultural fact to the user."
  input_template: |
    Write a very short, motivational tip for language learning. It can be something about grammar or vocabulary.
    It must be written in English, and must relate to the language the user is learning: {{ language }}.
    Adjust the tone and difficulty to match a {{ user_level }} user.
    Important rules:
    - Only write in English, even if the language learned is different.
    - The topic must concern the language the user is learning, {{ language }}.
    - Keep it under three sentences total.
    - Be positive and motivational.
    - Do not add extra explanations or apologies.

  expected_output: "A short motivational tip regarding learning, or vocabulary or grammar of {{language}}, answer fully in English."

quiz_task:
  description: "Create and evaluate a language quiz for the user."
  input_template: |
    Create a multiple-choice quiz entirely in {{ language }} with {{ num_questions }} questions.
    For each question:
    - Provide 4 options (all in {{ language }}).
    - Clearly mark the correct answer using the zero-based index (0, 1, 2, or 3).

    Important rules:
    - Do not explain answers, only provide the JSON structure.
    - Keep the language appropriate for a {{ user_level }} learner.
    - Format the response strictly as valid JSON.

  expected_output: "A valid JSON containing questions, options, and correct answers."
