level_task:
  description: "Generate a language-learning fill-in-the-blank question entirely in the target language."
  input_template: |
    You are a language learning assistant.

    Your task is to generate a fill-in-the-blank multiple choice question written entirely in the target language: {{ language }}.

    The purpose is to test the user's knowledge of {{ language }} based on their proficiency level: {{ user_level }} (e.g., Beginner, Intermediate, Advanced).

    The sentence must:
    - Be in {{ language }}
    - Contain one blank represented as '____'
    - Focus on vocabulary, grammar, sentence structure, or cultural expressions

    The options must:
    - Be exactly 4 choices
    - Be written in {{ language }}
    - Contain only one correct answer

    Output format:
    {
      "question": "A sentence in {{ language }} with one blank",
      "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
      "answer": 0
    }
    Do not include any explanation, metadata, or content in English. Only return a valid JSON object with the specified keys.
    DO NOT ENUMERATE THE OPTIONS, just provide them in the array.
  expected_output: "A valid JSON object containing 'question', 'options', and 'answer'."



tip_task:
  description: "Send a daily language learning tip fact to the user."
  input_template: |
    Write a very short, motivational tip for language learning. It can either be something about grammar or vocabulary.
    It must be written in English, and must relate to the language the user is learning: {{ language }}.
    Adjust the tone and difficulty to match a {{ user_level }} user, so increase the complexity for higher levels.
    Important rules:
    - Only write in English, even if the language learned is different.
    - The topic MUST concern the language the user is learning, {{ language }}.
    - Keep it UNDER three sentences total, use a maximum of 250 characters without trimming any words, be concise and to the point.
    - Be positive and motivational.
    - Do not add extra explanations or apologies.
    - Try to search for interesting topics that are not too common, vocabulary that you can use in daily life.
    - You must follow the user's language level, so if the user is a beginner, do not use complex grammar or vocabulary. Follow this table:

    | Level           | Level Characteristics                     |
    |-----------------|-------------------------------------------|
    | Beginner        | Basic vocabulary, simple sentences        |
    | Pre-Intermediate| Common expressions, basic tenses          |
    | Intermediate    | Complex sentences, some idioms            |
    | Pre-Advanced    | Abstract concepts, technical terms        |
    | Advanced        | Specialized vocabulary, nuanced meaning   |
    | Master          | Near-native complexity, cultural context  |
  expected_output: "A short motivational tip regarding learning, or vocabulary or grammar of {{language}}, answer fully in English."

quiz_task:
  description: "Create and evaluate multiple language quizzes for the user."
  input_template: |
    Create {{ num_quizzes }} multiple-choice quizzes entirely in {{ language }}, each containing {{ num_questions }} questions.

    For each question in each quiz:
    - Provide a 'sentence': a complete sentence in {{ language }} with **one missing word**, indicated by '____'.
    - Provide 4 options (all in {{ language }}) to fill in the blank.
    - Mark the correct answer by its zero-based index (0, 1, 2, or 3).

    The quizzes must match the {{ user_level }} according to these guidelines:
    | Level            | Characteristics                                 |
    |------------------|--------------------------------------------------|
    | Beginner         | Basic vocabulary, very simple sentences         |
    | Pre-Intermediate | Common expressions, basic tenses                |
    | Intermediate     | More complex sentences, some idiomatic usage    |
    | Pre-Advanced     | Abstract ideas, technical terms introduced      |
    | Advanced         | Specialized vocabulary, nuanced meaning         |
    | Master           | Near-native complexity, cultural or literary references |

    Important rules:
    - Do not explain answers, only provide the JSON structure.
    - Keep the language, sentence structure, and vocabulary appropriate for the {{ user_level }}.
    - Format the response strictly as valid JSON.
    - The JSON must contain exactly {{ num_quizzes }} arrays, each array containing {{ num_questions }} question objects.
    !!! IMPORTANT: The output MUST be a raw JSON string only. Do NOT include any formatting such as ```json blocks, titles, or explanations. !!!
  expected_output: "A valid JSON array containing {{ num_quizzes }} arrays, each with {{ num_questions }} questions, where each question has 'question', 'options', and 'answer'."